### ISSUE TITLE
Problem rendering Dictionary classs which implements an Enumerator which is not castable to IEnumerable

### ISSUE THREAD

**Issue by Hejle** [MoaidHathot/Dumpify#12]
I was trying to dump a NewtonSoft Json object, when I ran into the following error:
Unable to cast object of type '<GetEnumerator>d__64' to type 'System.Collections.IEnumerable'.

I tried the same with System.Text.Json and got a familiar exception:
Unable to cast object of type '<GetEnumerator>d__18[System.Text.Json.Nodes.JsonNode]' to type 'System.Collections.IEnumerable'.

```
[Failed to Render Newtonsoft.Json.Linq.JObject - {
  "key1": "value1",
  "key2": "value2"
}]. Unable to cast object of type '<GetEnumerator>d__64' to type 'System.Collections.IEnumerable'.
[Failed to Render System.Text.Json.Nodes.JsonObject - {
  "key1": "value1",
  "key2": "value2"
}]. Unable to cast object of type '<GetEnumerator>d__18[System.Text.Json.Nodes.JsonNode]' to type 'System.Collections.IEnumerable'.
```
I have created a fix for this which I will create a pullrequest for in a bit.

____________________________________________________

Note:
Even with the fix, I wouldn't say that Json is Supported.
The output after my Pull Request would look like this:
![billede](https://github.com/MoaidHathot/Dumpify/assets/18572997/d8594c63-1841-416f-9b85-1b85e6f56576)

To get NewtonSofts output to look nice, it is possible to add a CustomRenderer like this, which will format the output nicely:
```csharp
DumpConfig.Default.AddCustomTypeHandler(typeof(JValue), (obj, _, _, _) => obj.ToString());

       JObject
┌────────┬──────────┐
│ Key    │ Value    │
├────────┼──────────┤
│ "key1" │ "value1" │
│ "key2" │ "value2" │
└────────┴──────────┘
```

**Comment by MoaidHathot** [comment]
Good catch @Hejle!
Thank you for reporting this and creating the PR, it is awesome :)
I have added a small comment to the PR. Once you resolve it, I will merge it to the Main branch.

Regarding better renderers for Json support- I agree, this is something that we should take care of. If you want, you can be the champion of this feature. Although first we should outline which changes we want to do, which types we want to custom-render and how much we want to "hide", since every time we add custom renderers for types we hide some of the members of that types, and which otherwise will be shown, we should find the balance.
