### ISSUE TITLE
Dumping characters is not displaying properly

### ISSUE THREAD

**Issue by ruairica** [MoaidHathot/Dumpify#21]
Dumping a char doesn't display correctly, as a guess it looks like it is supposed to show a table with the character and then it's ascii value but on only the table headers are shown.
![image](https://github.com/MoaidHathot/Dumpify/assets/60053464/4ab291d4-b6ab-480a-823c-f2d754e90d8c)

**Comment by MoaidHathot** [comment]
Hi @ruairica, thanks for reporting this!
I just pushed a fix to this bug in commit 0118cd5. It will be part of the next version that should be released before the end of the month :)

**Comment by MoaidHathot** [comment]
Hi @ruairica, the fix is now published and is part of the https://github.com/MoaidHathot/Dumpify/releases/tag/0.6.4 release.

I applied the same fix for `nuint` and `nint` as well. In addition, I added the option to choose whether a char should be rendered with or without a surrounding character like`'` (`'a'`, `'b'`, etc...) and the option to choose the surrounding character.

Thanks for reporting this issue!
